### ISSUE TITLE
CenterPoint also gets Waymo support now

### ISSUE THREAD

**Issue by tianweiy** [Hub-Tian/Awesome-3D-Detectors#1]
https://github.com/tianweiy/CenterPoint

Great if you can update the description

**Comment by Hub-Tian** [comment]
Wonderful!!! It is updated. BTW, will kitti or more datasets be supported in the near future?

**Comment by tianweiy** [comment]
thanks! Lyft / Argoverse are probably in our plan but we need to see :)
